/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GiftCard { 'balance' : number, 'code' : string }
export interface MenuItem {
  'name' : string,
  'category' : [] | [string],
  'price' : number,
}
export interface _SERVICE {
  'addMenuItem' : ActorMethod<[string, number, [] | [string]], undefined>,
  'completeTransaction' : ActorMethod<
    [Array<MenuItem>, number, string],
    undefined
  >,
  'editMenuItem' : ActorMethod<
    [bigint, string, number, [] | [string]],
    undefined
  >,
  'getGiftCard' : ActorMethod<[string], GiftCard>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuByCategory' : ActorMethod<[], Array<MenuItem>>,
  'issueGiftCard' : ActorMethod<[string, number], undefined>,
  'removeMenuItem' : ActorMethod<[bigint], undefined>,
  'useGiftCard' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];