/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
});
export const GiftCard = IDL.Record({
  'balance' : IDL.Float64,
  'code' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func([IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)], [], []),
  'completeTransaction' : IDL.Func(
      [IDL.Vec(MenuItem), IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'editMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getGiftCard' : IDL.Func([IDL.Text], [GiftCard], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuByCategory' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'issueGiftCard' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'removeMenuItem' : IDL.Func([IDL.Nat], [], []),
  'useGiftCard' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
  });
  const GiftCard = IDL.Record({ 'balance' : IDL.Float64, 'code' : IDL.Text });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'completeTransaction' : IDL.Func(
        [IDL.Vec(MenuItem), IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'editMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getGiftCard' : IDL.Func([IDL.Text], [GiftCard], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuByCategory' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'issueGiftCard' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'removeMenuItem' : IDL.Func([IDL.Nat], [], []),
    'useGiftCard' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };